Dump S??network interface init-script error context to the console.
Upon error returned by a respective interface init-script, dump the captured
messages to the console.

Bug 8439.

diff --git a/board/laird/rootfs-additions-common/etc/init.d/S40network b/board/laird/rootfs-additions-common/etc/init.d/S40network
--- a/board/laird/rootfs-additions-common/etc/init.d/S40network
+++ b/board/laird/rootfs-additions-common/etc/init.d/S40network
@@ -15,13 +15,13 @@
 # contact: ews-support@lairdtech.com
 
 # network - init script for all network interface devices
-# 20120522
+# 20120522/20151214
 #
 # This init-script serves to stop/start/restart all "auto" enabled interfaces
 # by checking the '/etc/network/interfaces' (/e/n/i) file.
 #
-# The /e/n/i file is parsed for '^auto <iface>' at each interface stanza. 
-# Alternately, this script can be invoked with a specific interface to act on. 
+# The /e/n/i file is parsed for '^auto <iface>' at each interface stanza.
+# Alternately, this script can be invoked with a specific interface to act on.
 #
 # Other setup-scripts in '/etc/network' and in '/etc/init.d/opt' may be called,
 # as necessary to create/remove an interface.  Most operations backgrounded.
@@ -77,7 +77,7 @@ fi
 # Parse the /e/n/i for '^auto <iface>' enabled stanzas, in lieu of given iface.
 # The device-list order is as in /e/n/i for 'start', and reversed for 'stop'.
 case $1 in
-  stop|start) ## check /e/n/i 
+  stop|start) ## check /e/n/i
     ls=; devls=$( sed -n 's/^auto \([a-z][a-z0-9]*\).*$/\1/p' $eni )
     test $1 != start && for dev in $devls; do ls=$dev\ $ls; done && devls=$ls
     ;;
@@ -97,18 +97,19 @@ iface() {
   pid=$( sh -c 'echo $PPID' )
   logger -pinfo -s -tnetwork\[$pid\] -- $* 2>&1
 
-  up=false
-  dn=false
-  case $2 in
-    u*) up=true;;
-    d*) dn=true;;
-  esac
+  [ -z ${2/u*} ] && up=true || up=false
+  [ -z ${2/d*} ] && dn=true || dn=false
+
+  fail() { stat=error err=$?; break; }
+  stat=done
+  while :
+  do
   case $1 in
     lo) ## loopback support
       $tm $ifrc $1 $2 &
       $dn && wait && $tm $ifconfig $1 $2
       ;;
-    
+
     eth*) ## ethernet device support
       # must re-exec using alias for non-wired-ethernet devices; exit if tm
       [ -d /sys/class/net/$1/wireless ] \
@@ -127,15 +128,15 @@ iface() {
       $dn && wait && $tm $ifconfig $1 $2
       ;;
 
-    ppp*) ## point-to-point protocol support 
+    ppp*) ## point-to-point protocol support
       $dn && $tm $ifrc $1 $2
-      $tm $pppd $3
+      $tm $pppd $3 || fail
       $up && $tm $ifrc $1 $2 &
       ;;
 
     usb*) ## usb-g_ether support
       $dn && $tm $ifrc $1 $2
-      $tm $g_ether $3
+      $tm $g_ether $3 || fail
       $up && $tm $ifrc $1 $2 $4 &
       ;;
 
@@ -144,14 +145,14 @@ iface() {
       # the wireless script handles device up/down
       # and the ifrc script will handle configuration
       $dn && $tm $ifrc -x $1 $2
-      $tm $wifi $3
+      $tm $wifi $3 || fail
       $up && $tm $ifrc $1 $2 $4 &
       $dn && wait
       ;;
 
     br*) ## bridge-mode support
       $dn && $tm $ifrc $1 $2
-      $tm $bridge $3 $1
+      $tm $bridge $3 $1 || fail
       $up && $tm $ifrc $1 $2 $4 &
       ;;
 
@@ -159,12 +160,19 @@ iface() {
       echo \ \ ...unhandled interface name
       ;;
   esac
-  logger -pinfo -s -tnetwork\[$pid\] -- done 2>&1
+  break
+  done
+  logger -pinfo -s -tnetwork\[$pid\] -- $stat 2>&1
+  return $err
 }
 
 save_log_of() {
-  echo "network: $1 available" >>$lf
-  sed 's/\(.*\)network\[[0-9]*\]:.* [rs][et].*/\1\n&\2/' $log.$1 >>$log
+  # args: <dev> <status>
+  echo "network: $1 status:$2" >>$lf
+  # consolidate logged messages; display them on error
+  let 0+$2 && { xc=console; echo -e "\n$log.$1:$2" >/dev/$xc; } || xc=null
+  sed 's/[<>0-9]\+... .. \(.*network\[[0-9]*\]:.* [ersd]...*\)/\1/' $log.$1 \
+    |tee -a $log >/dev/$xc
   rm -f $log.$1
 } 2>/dev/null
 
@@ -226,7 +234,7 @@ case $act in
       # skip auto starting for bridge-mode ports
       case ${bpls##*ports } in *${dev:-X}*) continue;; esac
       #
-      ( iface $dev up $act $meth >>$log.$dev; save_log_of $dev )&
+      ( iface $dev up $act $meth >>$log.$dev; save_log_of $dev $? )&
     done
     $msg ${alert:+\\\n \ $alert}
     ;;
