Improved parsing of the inetd.conf file and performing service pre-checks.
This mechanism allows both fast bootup and fast service daemon response.

Removed use of awk, replaced w/faster file read in the processing loop.
Fixed the routine to properly perform checks on enabled services only.
Cleaned up messaging.

Bug 5589.

diff --git a/board/laird/rootfs-additions-common/etc/init.d/S50inetd b/board/laird/rootfs-additions-common/etc/init.d/S50inetd
--- a/board/laird/rootfs-additions-common/etc/init.d/S50inetd
+++ b/board/laird/rootfs-additions-common/etc/init.d/S50inetd
@@ -1,28 +1,39 @@
 #!/bin/sh
 # inetd - super server initialization (nonblocking)
-# This allows using TCPwrappers to respond to a requested protocol. 
 #
-# Configure services that are enabled in /etc/inetd.conf, and then start inetd.
-# Each service daemon's init-script to be used, must reside in /etc/init.d/opt.
+# For enabled services in /etc/inetd.conf,  a pre-check is performed for each
+# daemon's init-script successfully found in /etc/init.d/opt/.
+#
+# Each init-script should have a 'check)' handler to prepare its service.
+# This allows using TCPwrappers to respond fast to a requested protocol.
 # jon.hefling@lairdtech.com
 
 rcS_log=${rcS_log:-/dev/null}
 
-inetd_daemon_check()
-{
-  for srv in `sed -n 's/^[#]*\([a-z]\+\).*/\1/p' /etc/inetd.conf 2>/dev/null`
+log() {
+  echo "$@" >>$rcS_log
+}
+
+inetd_daemon_check() {
+  while read -r a1 a2 a3 a4 a5 a6 a7
   do
     # parse daemon-executable, daemon-name, daemon-init-script
-    daemon_exec=$( awk /^$srv/'{ print $6 }' /etc/inetd.conf )
+    # via args list from the inetd.conf file
+    #
+    [ -z $a1 ] && continue
+    [ "${a1}" == "#" ] && continue
+    [ "${a1:0:2}" == "#!" ] && continue
+
+    srv=$a1
+    daemon_exec=$a6
     daemon_name=${daemon_exec##*/}
     daemon_init=/etc/init.d/opt/S??${daemon_name}
     #
     # check if this service daemon can be enabled
-    [ -n $daemon_name"" ] || { echo "  $srv is disabled"; continue; }
-    [ -x $daemon_exec"" ] || { echo "  $srv is n/a, missing"; continue; }
-    [ -x $daemon_init"" ] || { echo "  $srv init is n/a, disabled"; continue; }
+    [ ${daemon_name:0:1} == "#" ] && { log "  $srv is disabled"; continue; }
+    [ -x $daemon_exec"" ] || { log "  $srv is n/a, missing"; continue; }
+    [ -x $daemon_init"" ] || { log "  $srv check is n/a"; continue; }
     #
-    echo "  $srv is setting up..."
     # wait on any net-init firstly, to avoid conflicts due to excessive load
     # run an enabled daemon-init-script to perform a pre-check in background
     # ( this allows the service to be started quickly when actually needed )
@@ -30,7 +41,10 @@ inetd_daemon_check()
     #
     ( wait $net_init_pids; $daemon_init check >>$rcS_log; )&
     srv_init_pids=$srv_init_pids\ $!
-  done
+    log "  $daemon_init check - $!"
+    echo -n " $srv"
+
+  done < /etc/inetd.conf
 }
 
 # find any network and bridge init-script pids
@@ -50,20 +64,22 @@ case $1 in
     ;;
     
   start)
-    echo "Starting inetd services..."
+    echo -n "Checking inetd services..."
     # the config file is required
     if [ ! -f /etc/inetd.conf ]
     then
-      echo /etc/inetd.conf file missing, aborted
+      echo -e "\n  file /etc/inetd.conf is missing"
       exit 1
     fi
     inetd_daemon_check
+    echo
+    #
     # wait in background to run super server 
-    ( wait $srv_init_pids; /usr/sbin/inetd && echo "  inetd running" >>$rcS_log )&
+    ( wait $srv_init_pids; /usr/sbin/inetd && echo "  inetd ready" >>$rcS_log )&
     ;;
     
   stop)
-    echo "Stopping inetd services."
+    echo "Stopping inetd."
     killall inetd 2>/dev/null
     ;;
 
