cve-checker: Unzip the database into target build directory
bug 13917

diff --git a/support/scripts/update-dbs b/support/scripts/update-dbs
--- a/support/scripts/update-dbs
+++ b/support/scripts/update-dbs
@@ -2,36 +2,31 @@
 # Script to generate downlaod NVD-CVE database
 
 CACHE_DBS=$1
-year=`date +"%Y"`
-NIST_URL=https://nvd.nist.gov/download
-
-#download nvd-cve files
-download_files(){
-
-  wget -N --tries=3 --connect-timeout=10  --quiet $NIST_URL/nvdcve-$1.xml.gz --directory-prefix=$CACHE_DBS
-  if [ $? -ne 0 ]; then
-    echo " [ Download Failed nvdcve-$1.xml.gz ]"
-    if [ -f "$CACHE_DBS/nvdcve-$1.xml" ]; then
-      echo " [ Download Failed: File does exists in Cache nvdcve-$1.xml: continue... ]"
-      return
-    else
-      echo " [ Download Failed: File does not exists in Cache nvdcve-$1.xml: exiting... ]"
-      exit 1
-    fi
-  fi
-
-  gunzip --quiet --keep --force  $CACHE_DBS/nvdcve-$1.xml.gz
-}
+BUILD_CVE_DBS=$2
+year=$(date +"%Y")
+NIST_URL=https://nvd.nist.gov/download/nvdcve-{2002..$year}.xml.zip
+NIST_FILE=$CACHE_DBS/nvdcve-{2002..$year}.xml.zip
 
 echo "Caching NVD-CVE Database Files [ Started ]"
-echo -n "[ "
 
-cd $CACHE_DBS
+wget -N --tries=3 --connect-timeout=10 --quiet --directory-prefix=$CACHE_DBS $(eval "echo $NIST_URL")
 
-for i in $(seq -f "%04g" 2002 $year); do
-  download_files $i
-  echo -n '#'
-done
+if [ $? -ne 0 ]; then
+  for i in $(eval "echo $NIST_FILE"); do
+    if [ ! -f $i ]; then
+      echo " [ Download Failed $i ]"
+      exit 1
+    else
+      echo "[ Download Failed $i, using cached file ]"
+    fi
+  done
+fi
 
-echo " ] [ Done ]"
+unzip -qod $BUILD_CVE_DBS "$CACHE_DBS/nvdcve-*.xml.zip"
+
+if [ $? -ne 0 ]; then
+  echo " [ Unzip Failed nvdcve-*.xml.zip ]"
+  exit 1
+fi
+
 echo "Finished NVD-CVE Database [ Done ]"
