BZ22308: openssl-3 fips initialization
Calculate fips.so.hmac during build.
Remove libcrypto.so.3.hmac from build.

Verify fips.so.hmac during fipsInit.sh.

Add openssl-3 fipsinstall -verify to fips-set.

Bug: 22308

diff --git a/package/lrd/lrd-fips-utils/fips-set b/package/lrd/lrd-fips-utils/fips-set
--- a/package/lrd/lrd-fips-utils/fips-set
+++ b/package/lrd/lrd-fips-utils/fips-set
@@ -16,18 +16,41 @@
 
 # fips-set - set different fips mode
 
+# verify openssl-3 fips module
+openssl3_fipsinit() {
+	openssl fipsinstall -in /etc/ssl/fipsmodule.cnf \
+			-module /usr/lib/ossl-modules/fips.so \
+			-self_test_onload -verify -quiet
+	if [ $? -ne 0 ]; then
+		echo "ERROR: openssl-3 fips module verification failed"
+		return 1
+	fi
+	return 0
+}
+
+openssl_fipsinit() {
+	if [ -f /usr/lib/libcrypto.so.3 ]; then
+		openssl3_fipsinit
+	else
+		# no installation required
+		return 0
+	fi
+}
+
 warning() {
   echo "Changes will take effect after reboot"
 }
 
 case "${1}" in
   fips) ## set fips only
+    openssl_fipsinit || return 1
     fw_setenv fips_wifi  || return 1
     fw_setenv fips 1
     warning
     ;;
 
   fips_wifi) ## set fips wifi
+    openssl_fipsinit || return 1
     fw_setenv fips 1  || return 1
     fw_setenv fips_wifi 1
     warning
